name = "BoTorchOpt"
uuid = "ec14edaa-b110-45d8-b073-5b582e9ce5cd"
version = "0.1.0"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de>"]

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Printf = "1.11.0"
PyCall = "1.96.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
